sudo: false
language: scala
sbt_args: ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M
scala:
  - 2.12.0-M3
  - 2.11.7
  - 2.10.5
env:
  global:
    # this tells ScalaTest not to use certain ANSI escapes
    - TERM=dumb
    # secure keys
    - secure: RqnPLSv01Yo5Jrer77IFaux6ZmYWbPaHYynToHBwm20ue549FP009H1eXf5QgjdB6xATSMN/5dHO+J7HQzlOh8wQpygzOBEHXrY8VxYonrGTHvU1qF02T1TYzfqbuf6zD4dzpTOBcTjGpE5SMZNocppetmz9r2R25dGNPu3NmSs=
    - secure: Bl8T+QdWKHQYTLWi4Cyu3ioA5JUPvMVKBGDDWqBSUwShwBfVyFi9Imv5MLtDJJK5jh8LswZOWZ7og9FwdtaL/bnSt6/F8moRItoSNTn1Bn6Il8+PlIeDcgBd9TCXOApYqNNG1zQGnp++CKduq5UMRHCS9PsoHkgyh12UGw2ZH7U=
    - secure: NVXCXQEVFsGt6nN/H45giy8NL3CQ38gBmjIZrLRzFQU4NXLgQWzuRl7N/JCpfN3d4wg/o6vjs85oRxQCUmDwIvHopBFefni1r5u9tKLt4oigNDa3F/Lhyfod3on57BhgZ7oDVww0b0llAS41jLYEMNgrY0FPXgqjXux4F3kqUBQ=
    - secure: "B0nsGQT4MisUNSyZ9VqKYlOghx2tAFnyvyOlfEESYsqXmGiV/A7fw5+UYtXhYufF3iAh/2hEIoFmus2mCP5V3kBn1mt5DJ18nsBuYd/WGL/gIyPCwAay3EujGt3SFzyVMbP49i1gYGHfTojynUHIECtmeNIzUhnJNH1knvDuzNQ="

  matrix:
    # whether or not to run benchmarks
    - BENCH=false
    - BENCH=true
matrix:
  fast_finish: true
  allow_failures:
    # We allow builds to fail if they are running on non-standard Scala
    # versions, or if the failure was due to benchmarks rather than unit tests.
    - scala: 2.12.0-M3
    - scala: 2.10.5
    - env: BENCH=true
  exclude:
    - scala: 2.12.0-M3
      env: BENCH=true
    - scala: 2.10.5
      env: BENCH=true
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
script:
  - sbt compile
  - | # if this is not the benchmark build, run the unit tests
      if [ $BENCH = "false" ]; then
        sbt clean coverage test
      fi
  - | # if this build is the benchmark build, run the benchmarks instead
      if [ $BENCH = "true" ]; then
        sbt bench:test
      fi
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - | # if we didn't run benchmarks, update code coverage
      if [ $BENCH = "false" ]; then
        bash <(curl -s https://codecov.io/bash) &&
        sbt coverageReport &&
        sbt coverageAggregate &&
        sbt codacyCoverage
      fi
  - | # if we are on the release scala version, check dependency versions
      if [ $TRAVIS_SCALA_VERSION = "2.11.8" ]; then
        sbt versioneye:updateProject versioneye:licenseCheck
      fi
  - |
      test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${BENCH}" = 'false' &&
      test "${TRAVIS_SCALA_VERSION}" = '2.11.7' &&
      sh "$TRAVIS_BUILD_DIR/.travis/bintray-credentials.sh" &&
      sbt 'set version := version.value + "+" + System.getenv("TRAVIS_BUILD_NUMBER")' publish
before_deploy:
  - sbt clean package
  - export RELEASE_JAR=$(ls target/scala-2.11/util_2.11*.jar)
  - echo "deploying $RELEASE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: QZZvnJfZGlhFsXKdh5mOxvvS8cn6TIYfsbrzmuEDO77Dj6gs2pG4JkOTYrO3omg55sMnG5CFywTJlszNwnuA/Ss3XlO5aB4h+5LnL4RPdI5f5bib20mliwjBGJ2z0C8eU7TCQUIb4yNVWtFbF4sEfl3kMoa7uvMO5j8grEWxpY4=
  file: "${RELEASE_JAR}"
  file_glob: true
  on:
    repo: hawkw/scala-common
    scala: 2.11.7
    tags: true
after_deploy:
  - sbt publish
  - .travis/publish_scaladoc.sh
